---
title: 'RMarkdown:  In Class Assignment'
author: "Hannah Kendziora"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

## Wise Words
> "Dont wait. The time will never be just right." 

[HK Favorite quote](https://www.invajy.com/25-inspirational-quotes-to-make-you-think/)

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

## My Semester
| __Course Number__ | _Course Title_     | Instructor name      |
|:------------------|:-------------------|:---------------------|
| __2311__          | _Computer Science_ | John Henderson       | 
| __2401__          | _Data Science_     | Katherine Shoemaker  |
| __2422__          | _Math_             | Edwin Tecarro        |
| __1301__          | _Freshmen Seminar_ | Cyril Harris         |


3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     

## I recommend
### _Frank Ocean_
> "There will be mountains you wont move" 

+ Ivy
+ Self Control
+ White Ferrari
+ Novacane
+ Pink & White
+ Nikes

Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
